// ============================================
// FEED ERROR CODES
// ============================================

// Post Content Validation
export const TITLE_MIN_LENGTH = "TITLE_MIN_LENGTH"
export const TITLE_MAX_LENGTH = "TITLE_MAX_LENGTH"
export const CONTENT_MIN_LENGTH = "CONTENT_MIN_LENGTH"
export const CONTENT_MAX_LENGTH = "CONTENT_MAX_LENGTH"

// Post Tags Validation
export const POST_TAGS_INVALID = "POST_TAGS_INVALID"
export const POST_TAGS_LIMIT_EXCEEDED = "POST_TAGS_LIMIT_EXCEEDED"
export const POST_TAG_MIN_LENGTH = "POST_TAG_MIN_LENGTH"
export const POST_TAG_MAX_LENGTH = "POST_TAG_MAX_LENGTH"
export const POST_TAG_FORMAT_INVALID = "POST_TAG_FORMAT_INVALID"

// Rate Limit Errors
export const CREATE_POST_IP_RATE_LIMIT_EXCEEDED = "CREATE_POST_IP_RATE_LIMIT_EXCEEDED"
export const CREATE_POST_USER_RATE_LIMIT_EXCEEDED = "CREATE_POST_USER_RATE_LIMIT_EXCEEDED"
export const TOGGLE_LIKE_FAVORITE_RATELIMIT_EXCEEDED = "TOGGLE_LIKE_FAVORITE_RATELIMIT_EXCEEDED"
export const FEED_SEARCH_RATELIMIT_EXCEEDED = "FEED_SEARCH_RATELIMIT_EXCEEDED"
export const GET_PROFILE_POSTS_RATELIMIT_EXCEEDED = "GET_PROFILE_POSTS_RATELIMIT_EXCEEDED"
export const GET_PROFILE_FAVORITES_RATELIMIT_EXCEEDED = "GET_PROFILE_FAVORITES_RATELIMIT_EXCEEDED"
export const GET_FEED_RATELIMIT_EXCEEDED = "GET_FEED_RATELIMIT_EXCEEDED"

// Service Layer Error
export const POST_CREATION_FAILED = "POST_CREATION_FAILED"

// Like Error
export const TOGGLE_LIKE_FAILED = "TOGGLE_LIKE_FAILED"
export const POST_NOT_FOUND = "POST_NOT_FOUND"

export type FeedErrorCode =
    | typeof TITLE_MIN_LENGTH
    | typeof TITLE_MAX_LENGTH
    | typeof CONTENT_MIN_LENGTH
    | typeof CONTENT_MAX_LENGTH
    | typeof POST_TAGS_INVALID
    | typeof POST_TAGS_LIMIT_EXCEEDED
    | typeof POST_TAG_MIN_LENGTH
    | typeof POST_TAG_MAX_LENGTH
    | typeof POST_CREATION_FAILED
    | typeof POST_TAG_FORMAT_INVALID
    | typeof TOGGLE_LIKE_FAILED
    | typeof POST_NOT_FOUND
    | typeof CREATE_POST_IP_RATE_LIMIT_EXCEEDED
    | typeof CREATE_POST_USER_RATE_LIMIT_EXCEEDED
    | typeof FEED_SEARCH_RATELIMIT_EXCEEDED
    | typeof GET_PROFILE_POSTS_RATELIMIT_EXCEEDED
    | typeof GET_PROFILE_FAVORITES_RATELIMIT_EXCEEDED
    | typeof GET_FEED_RATELIMIT_EXCEEDED

